const icons = {
  crown:'♛', plus:'＋', history:'↺', back:'←', users:'♣', shield:'♠', trophy:'♛', league:'♜', groups:'♣', knockout:'⚡', check:'✓', next:'›', close:'×', music:'♫'
};
const formats = [
  { id:'liga', title:'Liga', icon:'league', note:'Todos contra todos', desc:'Ideal para una noche larga. Cada jugador se enfrenta al resto y gana quien sume más puntos.' },
  { id:'grupos', title:'Fase de grupos', icon:'groups', note:'Grupos de 2 o más', desc:'Sorteamos grupos equilibrados. Después podés clasificar a los mejores a la siguiente ronda.' },
  { id:'eliminatoria', title:'Eliminatoria directa', icon:'knockout', note:'Cantidad par', desc:'Partidos a todo o nada. Quien pierde queda afuera hasta coronar al campeón.' }
];
const history = [{name:'Copa del Asado',date:'12 jul 2026',players:8,winner:'Nico'},{name:'Torneo del Viernes',date:'28 jun 2026',players:6,winner:'La Negra'}];
const state = { screen:'home', step:1, names:[''], format:'', groups:[], music:false };
const root = document.querySelector('#root');
const esc = value => value.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const players = () => state.names.map(n=>n.trim()).filter(Boolean);
const button = (type, content, cls='') => `<button data-action="${type}" class="${cls}">${content}</button>`;

function header(){ return `<header class="topbar">${button('home',`<span class="brand-mark">${icons.crown}</span><span><strong>TRUCO</strong><small>DE BARRIO</small></span>`,'brand')}${button('music',`${icons.music}<span>${state.music?'Chamamé sonando':'Ambientación'}</span>`,`sound-btn ${state.music?'active':''}`)}</header>`; }
function home(){ return `<section class="hero"><div class="eyebrow"><span></span> LA MESA ESTÁ SERVIDA <span></span></div><h1>Donde hay amigos,<br>hay <em>revancha.</em></h1><p>Armá el torneo, repartí las cartas y que hable la mesa.</p><div class="home-actions">${button('create',`${icons.plus} Crear torneo ${icons.next}`,'primary huge')}${button('history',`${icons.history} Ver historial`,'secondary huge')}</div><div class="table-rule"><span>♠</span><span>03</span><span>♥</span><span>06</span><span>♣</span></div></section>`; }
function steps(){ return `<div class="steps">${[['1','Jugadores'],['2','Formato'],['3','Sorteo']].map(([n,l],i)=>`<div class="step ${state.step>=+n?'on':''}"><span>${state.step>+n?icons.check:n}</span><small>${l}</small></div>${i<2?`<div class="line ${state.step>+n?'on':''}"></div>`:''}`).join('')}</div>`; }
function heading(icon, kicker, title, subtitle){ return `<div class="panel-heading"><span class="section-icon">${icons[icon]}</span><div><p>${kicker}</p><h2>${title}</h2><span>${subtitle}</span></div></div>`; }
function participants(){ const count=players().length; return `<div class="panel">${heading('users','PASO 1 DE 3','¿Quiénes juegan?','Sumá a todos los participantes de esta noche.')}<div class="roster-head"><b>PARTICIPANTES</b><span>${count} ${count===1?'jugador':'jugadores'}</span></div><div class="name-list">${state.names.map((n,i)=>`<div class="name-row"><span>${String(i+1).padStart(2,'0')}</span><input data-name="${i}" value="${esc(n)}" placeholder="Nombre o apodo"><button data-remove="${i}" aria-label="Eliminar">${icons.close}</button></div>`).join('')}</div>${button('add',`${icons.plus} Agregar participante`,'add-player')}${count<2?'<p class="helper">Necesitás al menos 2 jugadores para continuar.</p>':''}<div class="panel-footer"><button data-action="next-step" class="primary" ${count<2?'disabled':''}>Elegir formato ${icons.next}</button></div></div>`; }
function formatPicker(){ const count=players().length; return `<div class="panel wide-panel">${heading('shield',`PASO 2 DE 3 · ${count} JUGADORES`,'Elegí cómo se juega','Cada formato tiene su propia mística.')}<div class="format-grid">${formats.map(f=>{const disabled=f.id==='eliminatoria'&&count%2!==0;return `<button data-format="${f.id}" ${disabled?'disabled':''} class="format-card ${state.format===f.id?'selected':''}"><span class="format-icon">${icons[f.icon]}</span><span class="format-title">${f.title}</span><span class="format-note">${disabled?'No disponible con cantidad impar':f.note}</span><span class="format-desc">${f.desc}</span><span class="radio">${state.format===f.id?'<span></span>':''}</span></button>`}).join('')}</div><div class="panel-footer"><button data-action="confirm" class="primary" ${!state.format?'disabled':''}>${state.format==='grupos'?'Realizar sorteo':'Confirmar formato'} ${icons.next}</button></div></div>`; }
function draw(){ const list=[...players()].sort(()=>Math.random()-.5), count=Math.floor(list.length/2); state.groups=Array.from({length:count},()=>[]); list.forEach((p,i)=>state.groups[i%count].push(p)); }
function cards(items,prefix){ return `<div class="groups-grid">${items.map((group,i)=>`<article class="group"><header>${prefix} ${prefix==='GRUPO'?String.fromCharCode(65+i):i+1}</header>${group.map((p,j)=>`<div><span>${j+1}</span><b>${esc(p)}</b></div>`).join('')}</article>`).join('')}</div>`; }
function result(){ const ps=players(), label=formats.find(f=>f.id===state.format).title; let body=''; if(state.format==='grupos') body=cards(state.groups,'GRUPO'); if(state.format==='eliminatoria'){const pairs=[];ps.forEach((p,i)=>i%2===0?pairs.push([p]):pairs.at(-1).push(p));body=cards(pairs,'CRUCE');} if(state.format==='liga') body=`<div class="league-list">${ps.map((p,i)=>`<div><span>${i+1}</span><b>${esc(p)}</b><small>0 PTS</small></div>`).join('')}</div>`; return `<div class="panel wide-panel result-panel"><div class="result-badge">${icons.trophy}</div><p class="result-kicker">TORNEO LISTO</p><h2>${label}</h2><p class="result-copy">${state.format==='grupos'?`El sorteo armó ${state.groups.length} grupos para ${ps.length} jugadores.`:`Formato confirmado para ${ps.length} jugadores.`}</p>${body}<div class="finish-actions">${state.format==='grupos'?button('redraw','Volver a sortear','secondary'):''}${button('home',`Guardar torneo ${icons.check}`,'primary')}</div></div>`; }
function flow(){ return `<section class="flow-wrap">${button('back',`${icons.back} Volver`,'back')}${steps()}${state.step===1?participants():state.step===2?formatPicker():result()}</section>`; }
function historyView(){ return `<section class="flow-wrap">${button('home',`${icons.back} Volver al inicio`,'back')}<div class="panel history-panel">${heading('history','MEMORIAS DE LA MESA','Historial','Las glorias y derrotas que no se olvidan.')}<div class="history-list">${history.map(h=>`<article><div class="history-cup">${icons.trophy}</div><div><h3>${h.name}</h3><p>${h.date} · ${h.players} jugadores</p></div><div class="winner"><small>CAMPEÓN</small><b>${h.winner}</b></div></article>`).join('')}</div><p class="demo-note">Historial de muestra — los próximos torneos aparecerán acá.</p></div></section>`; }
function render(){ root.innerHTML=`<main class="app-shell"><div class="backdrop"></div>${header()}${state.screen==='home'?home():state.screen==='create'?flow():historyView()}</main>`; }
function goHome(){ Object.assign(state,{screen:'home',step:1,format:'',groups:[]}); render(); }
root.addEventListener('input',e=>{ if(e.target.dataset.name!==undefined) state.names[+e.target.dataset.name]=e.target.value; });
root.addEventListener('keydown',e=>{ if(e.target.dataset.name!==undefined&&e.key==='Enter'){state.names.push('');render();setTimeout(()=>document.querySelector('.name-row:last-child input')?.focus());} });
root.addEventListener('click',e=>{ const remove=e.target.closest('[data-remove]'), format=e.target.closest('[data-format]'), action=e.target.closest('[data-action]')?.dataset.action; if(remove){state.names.splice(+remove.dataset.remove,1);if(!state.names.length)state.names=[''];render();return;} if(format){state.format=format.dataset.format;render();return;} if(action==='home')goHome(); if(action==='music'){state.music=!state.music;render();} if(action==='create'){state.screen='create';render();} if(action==='history'){state.screen='history';render();} if(action==='add'){state.names.push('');render();setTimeout(()=>document.querySelector('.name-row:last-child input')?.focus());} if(action==='back'){if(state.step===1)goHome();else{state.step--;render();}} if(action==='next-step'&&players().length>=2){state.step=2;render();} if(action==='confirm'&&state.format){if(state.format==='grupos')draw();state.step=3;render();} if(action==='redraw'){draw();render();} });
render();
