const icons = { crown:'♛', plus:'＋', history:'↺', back:'←', users:'♣', shield:'♠', trophy:'♛', league:'♜', groups:'♣', knockout:'⚡', check:'✓', next:'›', close:'×', music:'♫' };
const formats = [
  { id:'liga', title:'Liga', icon:'league', note:'Todos contra todos', desc:'Cada equipo se enfrenta al resto y suma puntos en la tabla.' },
  { id:'grupos', title:'Fase de grupos', icon:'groups', note:'Grupos de 2 o más', desc:'Sorteamos grupos equilibrados para luego clasificar a los mejores.' },
  { id:'eliminatoria', title:'Eliminación directa', icon:'knockout', note:'Llave y cruces', desc:'Partidos a todo o nada hasta coronar al campeón.' }
];
const modes = [
  { id:'one', title:'1 vs 1', name:'Individual', desc:'2 jugadores como mínimo' },
  { id:'two', title:'2 vs 2', name:'Parejas', desc:'Equipos de 2 jugadores' },
  { id:'three', title:'3 vs 3', name:'Tríos', desc:'Equipos de 3 · incluye Puntas' }
];
const history = [{name:'Copa del Asado',date:'12 jul 2026',players:8,winner:'Nico'},{name:'Torneo del Viernes',date:'28 jun 2026',players:6,winner:'La Negra'}];
const state = { screen:'home', step:1, names:[''], mode:'', format:'', teams:[], groups:[], groupCount:1, qualifiers:2, leagueOutcome:'standings', matches:[], bracketRounds:[], activeMatchId:null, reviewStage:'teams', tournamentLocked:false, music:false, score:{ us:0, them:0, target:30, winner:null, winnerOpen:false } };
const root = document.querySelector('#root');
const esc = value => value.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const players = () => state.names.map(n=>n.trim()).filter(Boolean);
const button = (type, content, cls='') => `<button data-action="${type}" class="${cls}">${content}</button>`;
const teamSize = () => ({ one:1, two:2, three:3 })[state.mode] || 1;
const isRosterValid = () => {
  const count=players().length, size=teamSize();
  return count>=size*2&&count<=48&&count%size===0;
};

function header(){ return `<header class="topbar">${button('home',`<span class="brand-mark">${icons.crown}</span><span><strong>TRUCO</strong><small>DE BARRIO</small></span>`,'brand')}${button('music',`${icons.music}<span>${state.music?'Chamamé sonando':'Ambientación'}</span>`,`sound-btn ${state.music?'active':''}`)}</header>`; }
function home(){ return `<section class="hero"><div class="eyebrow"><span></span> LA MESA ESTÁ SERVIDA <span></span></div><h1>Donde hay amigos,<br>hay <em>revancha.</em></h1><p>Armá el torneo, repartí las cartas y que hable la mesa.</p><div class="home-actions">${button('create',`${icons.plus} Crear torneo ${icons.next}`,'primary huge')}${button('scoreboard','Anotador','secondary huge')}${button('history',`${icons.history} Ver historial`,'secondary huge')}</div><div class="table-rule"><span>♠</span><span>03</span><span>♥</span><span>06</span><span>♣</span></div></section>`; }
function steps(){ return `<div class="steps">${[['1','Modalidad'],['2','Jugadores'],['3','Formato'],['4','Sorteo']].map(([n,l],i)=>`<div class="step ${state.step>=+n?'on':''}"><span>${state.step>+n?icons.check:n}</span><small>${l}</small></div>${i<3?`<div class="line ${state.step>+n?'on':''}"></div>`:''}`).join('')}</div>`; }
function heading(icon, kicker, title, subtitle){ return `<div class="panel-heading"><span class="section-icon">${icons[icon]}</span><div><p>${kicker}</p><h2>${title}</h2><span>${subtitle}</span></div></div>`; }
function modePicker(){ return `<div class="panel wide-panel">${heading('users','PASO 1 DE 4','Elegí la modalidad','El formato del torneo se elige después.')}<div class="mode-grid">${modes.map(m=>`<button data-mode="${m.id}" class="mode-card ${state.mode===m.id?'selected':''}"><span class="mode-number">${m.title}</span><b>${m.name}</b><small>${m.desc}</small><span class="radio">${state.mode===m.id?'<span></span>':''}</span></button>`).join('')}</div><div class="panel-footer"><button data-action="mode-next" class="primary" ${!state.mode?'disabled':''}>Cargar jugadores ${icons.next}</button></div></div>`; }
function participants(){
  const count=players().length, size=teamSize(), min=size*2;
  const valid=isRosterValid();
  const help=count<min?`Necesitás al menos ${min} jugadores para esta modalidad.`:count%size?`La cantidad debe ser múltiplo de ${size} para formar los equipos.`:count>48?'El máximo es de 48 jugadores.':'';
  return `<div class="panel">${heading('users','PASO 2 DE 4','¿Quiénes juegan?','Sumá a todos los participantes de esta noche.')}<div class="roster-head"><b>PARTICIPANTES</b><span>${count} ${count===1?'jugador':'jugadores'}</span></div><div class="name-list">${state.names.map((n,i)=>`<div class="name-row"><span>${String(i+1).padStart(2,'0')}</span><input data-name="${i}" value="${esc(n)}" placeholder="Nombre o apodo"><button data-remove="${i}" aria-label="Eliminar">${icons.close}</button></div>`).join('')}</div>${button('add',`${icons.plus} Agregar participante`,'add-player')}${!valid?`<p class="helper">${help}</p>`:''}<div class="panel-footer"><button data-action="players-next" class="primary" ${!valid?'disabled':''}>Elegir formato ${icons.next}</button></div></div>`;
}
function groupOptions(total){ return Array.from({length:Math.max(1,Math.floor(total/2))},(_,i)=>i+1).filter(count=>Math.floor(total/count)>=2&&Math.ceil(total/count)-Math.floor(total/count)<=1); }
function recommendedGroupCount(total){ const exact=groupOptions(total).filter(count=>total%count===0&&[2,3].includes(total/count)); return exact.at(-1)||groupOptions(total).at(-1)||1; }
function qualifierOptions(total){ return [2,4,8,16,32].filter(n=>n<=total); }
function formatConfiguration(){ const total=players().length/teamSize(); if(state.format==='grupos'){const options=groupOptions(total);return `<div class="format-config"><div><b>Cantidad de grupos</b><span>Recomendamos ${recommendedGroupCount(total)}</span></div><div class="choice-row">${options.map(n=>`<button data-group-count="${n}" class="${state.groupCount===n?'selected':''}">${n} ${n===1?'grupo':'grupos'}</button>`).join('')}</div><div><b>Clasifican a playoffs</b><span>La zona azul marcará los clasificados</span></div><div class="choice-row">${qualifierOptions(total).map(n=>`<button data-qualifiers="${n}" class="${state.qualifiers===n?'selected':''}">${n} equipos</button>`).join('')}</div></div>`;} if(state.format==='liga'){return `<div class="format-config"><div><b>¿Cómo se define el campeón?</b><span>Podés cambiarlo antes del sorteo</span></div><div class="choice-row"><button data-league-outcome="standings" class="${state.leagueOutcome==='standings'?'selected':''}">El primero es campeón</button><button data-league-outcome="playoffs" class="${state.leagueOutcome==='playoffs'?'selected':''}">Playoffs</button></div>${state.leagueOutcome==='playoffs'?`<div><b>Clasifican</b></div><div class="choice-row">${qualifierOptions(total).map(n=>`<button data-qualifiers="${n}" class="${state.qualifiers===n?'selected':''}">${n} equipos</button>`).join('')}</div>`:''}</div>`;} return ''; }
function formatPicker(){ const count=players().length; return `<div class="panel wide-panel">${heading('shield',`PASO 3 DE 4 · ${count} JUGADORES`,'Elegí cómo se juega','Cada formato tiene su propia mística.')}<div class="format-grid">${formats.map(f=>`<button data-format="${f.id}" class="format-card ${state.format===f.id?'selected':''}"><span class="format-icon">${icons[f.icon]}</span><span class="format-title">${f.title}</span><span class="format-note">${f.note}</span><span class="format-desc">${f.desc}</span><span class="radio">${state.format===f.id?'<span></span>':''}</span></button>`).join('')}</div>${formatConfiguration()}<div class="panel-footer"><button data-action="confirm" class="primary" ${!state.format?'disabled':''}>Confirmar participantes y sortear ${icons.next}</button></div></div>`; }
function createTeams(){
  const shuffled=[...players()].sort(()=>Math.random()-.5), size=teamSize();
  state.teams=[];
  for(let i=0;i<shuffled.length;i+=size){
    const members=shuffled.slice(i,i+size);
    state.teams.push({ id:`team-${i/size+1}`, name:size===1?members[0]:`Equipo ${i/size+1}`, members });
  }
}
function shuffle(list){ return [...list].sort(()=>Math.random()-.5); }
function drawGroups(){ const list=shuffle(state.teams); state.groups=Array.from({length:state.groupCount},(_,i)=>({id:`group-${i}`,name:`Grupo ${String.fromCharCode(65+i)}`,teams:[]})); list.forEach((team,i)=>state.groups[i%state.groupCount].teams.push(team)); }
function makeMatch(a,b,groupId=null,round=1){ return {id:`match-${crypto.randomUUID?.()||Math.random()}`,a:a.id,b:b.id,groupId,round,scoreA:null,scoreB:null,winnerId:null}; }
function roundRobin(teams,groupId=null){ const matches=[]; for(let i=0;i<teams.length;i++)for(let j=i+1;j<teams.length;j++)matches.push(makeMatch(teams[i],teams[j],groupId)); return shuffle(matches); }
function createTournament(){
  state.matches=[];state.bracketRounds=[];
  if(state.format==='grupos'){drawGroups();state.groups.forEach(group=>state.matches.push(...roundRobin(group.teams,group.id)));}
  if(state.format==='liga')state.matches=roundRobin(state.teams);
  if(state.format==='eliminatoria'){
    const entrants=shuffle(state.teams), first=[];
    for(let i=0;i<entrants.length;i+=2){if(entrants[i+1]){const match=makeMatch(entrants[i],entrants[i+1],null,1);state.matches.push(match);first.push(match.id);}}
    state.bracketRounds=[first];
  }
}
function teamById(id){ return state.teams.find(team=>team.id===id); }
function standings(teams,matches){ return teams.map(team=>{const row={team,played:0,wins:0,losses:0,points:0,for:0,against:0,diff:0};matches.filter(m=>m.scoreA!==null&&(m.a===team.id||m.b===team.id)).forEach(m=>{const home=m.a===team.id,a=home?m.scoreA:m.scoreB,b=home?m.scoreB:m.scoreA;row.played++;row.for+=a;row.against+=b;if(a>b){row.wins++;row.points+=3;}else row.losses++;});row.diff=row.for-row.against;return row;}).sort((a,b)=>b.points-a.points||b.diff-a.diff); }
function tableView(teams,matches,qualified=0){ const rows=standings(teams,matches);return `<div class="standings"><div class="table-head"><span>#</span><span>Equipo</span><span>PTS</span><span>J</span><span>G</span><span>P</span><span>+/-</span></div>${rows.map((row,i)=>`<div class="table-row ${i<qualified?'qualified':''}"><span>${i+1}</span><span class="table-team"><b>${esc(row.team.name)}</b><small>${row.team.members.map(esc).join(' · ')}</small></span><strong>${row.points}</strong><span>${row.played}</span><span>${row.wins}</span><span>${row.losses}</span><span class="${row.diff>0?'positive':row.diff<0?'negative':''}">${row.diff>0?'+':''}${row.diff}</span></div>`).join('')}${qualified?`<footer><i></i> Clasifican ${qualified} a playoffs</footer>`:''}</div>`; }
function fixturesView(matches,title='Partidos'){ return `<aside class="fixtures"><header>${title}<small>${state.tournamentLocked?`${matches.filter(m=>m.scoreA!==null).length}/${matches.length} jugados`:'Vista previa'}</small></header>${matches.map((match,i)=>{const a=teamById(match.a),b=teamById(match.b);return `<button ${state.tournamentLocked?`data-match="${match.id}"`:''} class="fixture ${state.tournamentLocked?'':'preview'}"><span class="date">FECHA ${i+1}</span><span><b>${esc(a.name)}</b><strong>${match.scoreA??'–'}</strong></span><span><b>${esc(b.name)}</b><strong>${match.scoreB??'–'}</strong></span></button>`}).join('')}</aside>`; }
function groupsDashboard(){ const base=Math.floor(state.qualifiers/state.groups.length),extra=state.qualifiers%state.groups.length;return `<div class="group-dashboards">${state.groups.map((group,index)=>{const matches=state.matches.filter(m=>m.groupId===group.id),qualified=Math.min(base+(index<extra?1:0),group.teams.length);return `<section class="competition-block"><h3>${group.name}</h3><div class="competition-layout">${tableView(group.teams,matches,qualified)}${fixturesView(matches)}</div></section>`}).join('')}</div>`; }
function leagueDashboard(){ return `<div class="competition-layout">${tableView(state.teams,state.matches,state.leagueOutcome==='playoffs'?state.qualifiers:0)}${fixturesView(state.matches,'Calendario')}</div>`; }
function roundName(size,index){ if(index===0&&size>8)return'Dieciseisavos';if(index===0&&size>4)return'Octavos';if(size/(2**index)>4)return'Cuartos';if(size/(2**index)>2)return'Semifinal';return'Final'; }
function bracketDashboard(){ const initial=Math.max(2,state.teams.length);const columns=[...state.bracketRounds];while(columns.length<Math.ceil(Math.log2(initial)))columns.push([]);return `<div class="bracket">${columns.map((ids,index)=>`<section><h3>${roundName(initial,index)}</h3><div class="round-matches">${ids.length?ids.map(id=>{const m=state.matches.find(x=>x.id===id),a=teamById(m.a),b=teamById(m.b);return `<button ${state.tournamentLocked?`data-match="${m.id}"`:''} class="bracket-match ${state.tournamentLocked?'':'preview'}"><span>${esc(a.name)} <b>${m.scoreA??'–'}</b></span><span>${esc(b.name)} <b>${m.scoreB??'–'}</b></span></button>`}).join(''):'<div class="pending-round">A definir</div>'}</div></section>`).join('')}</div>`; }
function teamsReview(){ return `<div class="tournament-dashboard team-review"><div class="dashboard-title"><p>SORTEO DE EQUIPOS</p><h2>Así quedaron los equipos</h2><span>Revisalos antes de generar el torneo.</span></div><div class="team-review-grid">${state.teams.map(team=>`<article><span>${team.name}</span>${team.members.map((member,i)=>`<div><b>${i+1}</b>${esc(member)}</div>`).join('')}</article>`).join('')}</div><div class="finish-actions">${button('reshuffle-teams','Sortear otra vez','secondary')}${button('accept-teams',`Confirmar equipos y continuar ${icons.next}`,'primary')}</div></div>`; }
function competitionReview(){ const label=formats.find(f=>f.id===state.format).title,mode=modes.find(m=>m.id===state.mode).title;return `<div class="tournament-dashboard ${state.tournamentLocked?'locked':''}"><div class="dashboard-title"><p>${state.tournamentLocked?'TORNEO CREADO':'REVISIÓN DEL SORTEO'} · ${mode} · ${state.teams.length} equipos</p><h2>${label}</h2><span>${state.tournamentLocked?'Tocá un enfrentamiento para abrir el anotador.':'Revisá el sorteo. Todavía podés cambiarlo.'}</span></div>${state.format==='grupos'?groupsDashboard():state.format==='liga'?leagueDashboard():bracketDashboard()}<div class="finish-actions">${state.tournamentLocked?button('home',`Guardar y salir ${icons.check}`,'primary'):`${button('reshuffle-competition','Volver a sortear','secondary')}${button('lock-tournament',`Confirmar y crear torneo ${icons.check}`,'primary')}`}</div></div>`; }
function result(){ return state.reviewStage==='teams'&&state.mode!=='one'?teamsReview():competitionReview(); }
function flow(){ return `<section class="flow-wrap">${state.tournamentLocked?button('home',`${icons.back} Salir del torneo`,'back'):button('back',`${icons.back} Volver`,'back')}${steps()}${state.step===1?modePicker():state.step===2?participants():state.step===3?formatPicker():result()}</section>`; }

function tallyGroup(value){ const marks=['top','right','bottom','left','slash']; return `<span class="tally-group">${marks.slice(0,value).map(mark=>`<i class="${mark}"></i>`).join('')}</span>`; }
function tally(score){ let left=score, html=''; while(left>0){const amount=Math.min(left,5);html+=tallyGroup(amount);left-=amount;} return html||'<span class="empty-score">Tocá para empezar</span>'; }
function advanceBracket(){ if(state.format!=='eliminatoria')return;const current=state.bracketRounds.at(-1).map(id=>state.matches.find(m=>m.id===id));if(!current.length||current.some(m=>m.scoreA===null)||state.bracketRounds.length>=Math.ceil(Math.log2(state.teams.length)))return;const winners=current.map(m=>teamById(m.winnerId)),next=[];for(let i=0;i<winners.length;i+=2)if(winners[i+1]){const match=makeMatch(winners[i],winners[i+1],null,state.bracketRounds.length+1);state.matches.push(match);next.push(match.id);}if(next.length)state.bracketRounds.push(next); }
function completeActiveMatch(side){ const match=state.matches.find(m=>m.id===state.activeMatchId);if(!match)return;match.scoreA=state.score.us;match.scoreB=state.score.them;match.winnerId=side==='us'?match.a:match.b;advanceBracket(); }
function winnerModal(){ if(!state.score.winner||!state.score.winnerOpen)return ''; const match=state.matches.find(m=>m.id===state.activeMatchId),label=match?esc(teamById(match.winnerId).name):(state.score.winner==='us'?'Nos':'Ellos'); return `<div class="winner-overlay" role="dialog" aria-modal="true" aria-labelledby="winner-title"><div class="winner-modal"><button data-action="close-winner" class="winner-close" aria-label="Cerrar">×</button><span class="winner-crown">${icons.crown}</span><p>PARTIDA TERMINADA</p><h2 id="winner-title">¡Ganó ${label}!</h2><span>Resultado final: ${state.score.us} a ${state.score.them}</span>${button(match?'return-tournament':'play-again',match?'Volver al torneo':'Volver a jugar','primary winner-again')}</div></div>`; }
function scoreboard(){ const {us,them,target}=state.score,match=state.matches.find(m=>m.id===state.activeMatchId),left=match?teamById(match.a).name:'Nos',right=match?teamById(match.b).name:'Ellos'; return `<section class="scoreboard-wrap"><div class="scoreboard-top">${button(match?'match-back':'home',`${icons.back} ${match?'Volver al torneo':'Volver'}`,'back')}<div class="target-switch"><span>PARTIDA A</span><button data-target="15" class="${target===15?'active':''}">15</button><button data-target="30" class="${target===30?'active':''}">30</button></div></div><div class="scoreboard"><header><span>${match?'PARTIDO DEL TORNEO':'ANOTADOR LIBRE'}</span><strong>Primero en llegar a ${target}</strong></header><div class="score-sides"><button class="score-side us" data-score="us" aria-label="Sumar un punto a ${esc(left)}"><span class="side-label">${esc(left)}</span><strong>${us}</strong><div class="tallies">${tally(us)}</div><small>TOCÁ PARA SUMAR</small></button><div class="score-divider"><span>${target}</span><i></i></div><button class="score-side them" data-score="them" aria-label="Sumar un punto a ${esc(right)}"><span class="side-label">${esc(right)}</span><strong>${them}</strong><div class="tallies">${tally(them)}</div><small>TOCÁ PARA SUMAR</small></button></div><footer><button data-minus="us">− ${esc(left)}</button>${button('reset-score','Reiniciar','reset-score')}<button data-minus="them">${esc(right)} −</button></footer></div>${winnerModal()}</section>`; }
function historyView(){ return `<section class="flow-wrap">${button('home',`${icons.back} Volver al inicio`,'back')}<div class="panel history-panel">${heading('history','MEMORIAS DE LA MESA','Historial','Las glorias y derrotas que no se olvidan.')}<div class="history-list">${history.map(h=>`<article><div class="history-cup">${icons.trophy}</div><div><h3>${h.name}</h3><p>${h.date} · ${h.players} jugadores</p></div><div class="winner"><small>CAMPEÓN</small><b>${h.winner}</b></div></article>`).join('')}</div><p class="demo-note">Historial de muestra — los próximos torneos aparecerán acá.</p></div></section>`; }
function render(){ root.innerHTML=`<main class="app-shell"><div class="backdrop"></div>${header()}${state.screen==='home'?home():state.screen==='create'?flow():state.screen==='scoreboard'?scoreboard():historyView()}</main>`; }
function goHome(){ Object.assign(state,{screen:'home',step:1,mode:'',format:'',teams:[],groups:[],matches:[],bracketRounds:[],activeMatchId:null,reviewStage:'teams',tournamentLocked:false}); render(); }

root.addEventListener('input',e=>{ if(e.target.dataset.name!==undefined) state.names[+e.target.dataset.name]=e.target.value; });
root.addEventListener('keydown',e=>{ if(e.target.dataset.name!==undefined&&e.key==='Enter'){state.names.push('');render();setTimeout(()=>document.querySelector('.name-row:last-child input')?.focus());} });
root.addEventListener('click',e=>{
  const remove=e.target.closest('[data-remove]'), format=e.target.closest('[data-format]'), mode=e.target.closest('[data-mode]'), match=e.target.closest('[data-match]'), groupCount=e.target.closest('[data-group-count]'), qualifiers=e.target.closest('[data-qualifiers]'), leagueOutcome=e.target.closest('[data-league-outcome]'), score=e.target.closest('[data-score]'), minus=e.target.closest('[data-minus]'), target=e.target.closest('[data-target]'), action=e.target.closest('[data-action]')?.dataset.action;
  if(remove){state.names.splice(+remove.dataset.remove,1);if(!state.names.length)state.names=[''];render();return;}
  if(format){state.format=format.dataset.format;const total=players().length/teamSize();state.groupCount=recommendedGroupCount(total);state.qualifiers=qualifierOptions(total).at(-1)||2;render();return;}
  if(mode){state.mode=mode.dataset.mode;render();return;}
  if(groupCount){state.groupCount=+groupCount.dataset.groupCount;render();return;}
  if(qualifiers){state.qualifiers=+qualifiers.dataset.qualifiers;render();return;}
  if(leagueOutcome){state.leagueOutcome=leagueOutcome.dataset.leagueOutcome;render();return;}
  if(match){const selected=state.matches.find(m=>m.id===match.dataset.match);state.activeMatchId=selected.id;state.score.us=selected.scoreA??0;state.score.them=selected.scoreB??0;state.score.winner=selected.winnerId?(selected.winnerId===selected.a?'us':'them'):null;state.score.winnerOpen=false;state.screen='scoreboard';render();return;}
  if(score){const side=score.dataset.score;if(!state.score.winner&&state.score[side]<state.score.target){state.score[side]++;if(state.score[side]===state.score.target){state.score.winner=side;state.score.winnerOpen=true;completeActiveMatch(side);}}render();return;}
  if(minus){const side=minus.dataset.minus;if(!state.score.winner)state.score[side]=Math.max(0,state.score[side]-1);render();return;}
  if(target){state.score.target=+target.dataset.target;state.score.us=Math.min(state.score.us,state.score.target);state.score.them=Math.min(state.score.them,state.score.target);state.score.winner=null;state.score.winnerOpen=false;render();return;}
  if(action==='home')goHome();
  if(action==='music'){state.music=!state.music;render();}
  if(action==='create'){state.screen='create';render();}
  if(action==='scoreboard'){state.screen='scoreboard';render();}
  if(action==='history'){state.screen='history';render();}
  if(action==='match-back'||action==='return-tournament'){state.screen='create';state.activeMatchId=null;state.score.winnerOpen=false;render();}
  if(action==='add'&&state.names.length<48){state.names.push('');render();setTimeout(()=>document.querySelector('.name-row:last-child input')?.focus());}
  if(action==='back'){if(state.step===1)goHome();else{state.step--;render();}}
  if(action==='mode-next'&&state.mode){state.step=2;render();}
  if(action==='players-next'&&isRosterValid()){state.step=3;render();}
  if(action==='confirm'&&state.format&&isRosterValid()){createTeams();state.tournamentLocked=false;if(state.mode==='one'){createTournament();state.reviewStage='competition';}else state.reviewStage='teams';state.step=4;render();}
  if(action==='reshuffle-teams'){createTeams();render();}
  if(action==='accept-teams'){createTournament();state.reviewStage='competition';render();}
  if(action==='reshuffle-competition'){createTournament();render();}
  if(action==='lock-tournament'){state.tournamentLocked=true;render();}
  if(action==='reset-score'||action==='play-again'){state.score.us=0;state.score.them=0;state.score.winner=null;state.score.winnerOpen=false;render();}
  if(action==='close-winner'){state.score.winnerOpen=false;render();}
});
render();
