const lineIcon=(content)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${content}</svg>`;
const icons = { crown:lineIcon('<path d="M4 8l4 3 4-6 4 6 4-3-2 10H6z"/><path d="M7 21h10"/>'), plus:'＋', history:'↺', back:'←', users:lineIcon('<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.3"/><path d="M3.5 19c.5-4 2.4-6 5.5-6s5 2 5.5 6M14 14c3.4-.7 5.6 1 6.3 4"/>'), shield:lineIcon('<path d="M12 3 20 6v5c0 5-3.2 8.2-8 10-4.8-1.8-8-5-8-10V6z"/><path d="m8.5 12 2.2 2.2 4.8-5"/>'), trophy:lineIcon('<path d="M8 4h8v5c0 3-1.6 5-4 5s-4-2-4-5zM12 14v4M8 21h8M9 18h6M8 7H4c0 3 1.5 5 4.5 5M16 7h4c0 3-1.5 5-4.5 5"/>'), league:lineIcon('<path d="M5 5h14M5 10h14M5 15h14M5 20h14"/><circle cx="8" cy="5" r="1"/><circle cx="14" cy="10" r="1"/><circle cx="10" cy="15" r="1"/><circle cx="17" cy="20" r="1"/>'), groups:lineIcon('<circle cx="8" cy="8" r="2.5"/><circle cx="16" cy="8" r="2.5"/><circle cx="8" cy="16" r="2.5"/><circle cx="16" cy="16" r="2.5"/>'), knockout:lineIcon('<path d="M6 4h4v5h4V4h4M10 9v4h4V9M12 13v7"/>'), check:'✓', next:'›', close:'×', music:'♫', settings:'⚙' };
const formats = [
  { id:'liga', title:'Liga', icon:'league', note:'Todos contra todos', desc:'Cada equipo se enfrenta al resto y suma puntos en la tabla.' },
  { id:'grupos', title:'Fase de grupos', icon:'groups', note:'Grupos de 2 o más', desc:'Sorteamos grupos equilibrados para luego clasificar a los mejores.' },
  { id:'eliminatoria', title:'Eliminación directa', icon:'knockout', note:'Llave y cruces', desc:'Partidos a todo o nada hasta coronar al campeón.' }
];
const modes = [
  { id:'one', title:'1 vs 1', name:'Individual', desc:'2 jugadores como mínimo' },
  { id:'two', title:'2 vs 2', name:'Parejas', desc:'Equipos de 2 jugadores' },
  { id:'three', title:'3 vs 3', name:'Tríos', desc:'Equipos de 3 · incluye Puntas' }
];
const demoHistory = [{id:'demo-1',name:'Copa del Asado',date:'12 jul 2026',players:8,winner:'Nico',matches:[]},{id:'demo-2',name:'Torneo del Viernes',date:'28 jun 2026',players:6,winner:'La Negra',matches:[]}];
const state = { screen:'home', settingsReturnScreen:'home', step:1, names:[''], mode:'', format:'', teams:[], groups:[], groupCount:1, qualifiers:2, leagueOutcome:'standings', matches:[], bracketRounds:[], bracketSize:0, phase:'regular', playoffView:'bracket', fixturePages:{}, activeMatchId:null, selectedHistoryId:null, reviewStage:'teams', tournamentLocked:false, tournamentCompleted:false, championId:null, championOpen:false, music:false, puntasEnabled:localStorage.getItem('truco-criollo-puntas')!=='false', uiSoundsEnabled:localStorage.getItem('truco-criollo-ui-sounds')!=='false', score:{ us:0, them:0, target:30, winner:null, winnerOpen:false, roundType:'Redonda', roundNotice:false } };
const root = document.querySelector('#root');
const ambientAudio = new Audio('/public/audio/ambientacion.mp3');
ambientAudio.loop = true;
ambientAudio.preload = 'auto';
ambientAudio.volume = 0.28;
let handTimer=null;
let roundNoticeTimer=null;
let lastViewSignature='';
let uiAudioContext=null;
const esc = value => value.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const players = () => state.names.map(n=>n.trim()).filter(Boolean);
const button = (type, content, cls='') => `<button data-action="${type}" class="${cls}">${content}</button>`;
const teamSize = () => ({ one:1, two:2, three:3 })[state.mode] || 1;
const isRosterValid = () => {
  const count=players().length, size=teamSize();
  return count>=size*2&&count<=48&&count%size===0;
};
const savedTournamentKey='truco-de-barrio-active-tournament';
const tournamentHistoryKey='truco-de-barrio-history';
let history=(()=>{try{return JSON.parse(localStorage.getItem(tournamentHistoryKey))||demoHistory;}catch{return demoHistory;}})();
function saveTournament(){ if(!state.tournamentLocked||state.tournamentCompleted)return;const data={names:state.names,mode:state.mode,format:state.format,teams:state.teams,groups:state.groups,groupCount:state.groupCount,qualifiers:state.qualifiers,leagueOutcome:state.leagueOutcome,matches:state.matches,bracketRounds:state.bracketRounds,bracketSize:state.bracketSize,phase:state.phase,playoffView:state.playoffView,fixturePages:state.fixturePages,reviewStage:'competition',tournamentLocked:true,tournamentCompleted:false,championId:null,championOpen:false,step:4};localStorage.setItem(savedTournamentKey,JSON.stringify(data)); }
function restoreTournament(){ try{const data=JSON.parse(localStorage.getItem(savedTournamentKey));if(data?.tournamentLocked)Object.assign(state,data,{phase:data.phase||(data.format==='eliminatoria'?'playoffs':'regular'),bracketSize:data.bracketSize||(data.format==='eliminatoria'?data.teams?.length:0),tournamentCompleted:false,championId:null,championOpen:false,screen:'home',activeMatchId:null});}catch{localStorage.removeItem(savedTournamentKey);} }
function resetTournament(){ localStorage.removeItem(savedTournamentKey);Object.assign(state,{screen:'create',step:1,names:[''],mode:'',format:'',teams:[],groups:[],groupCount:1,qualifiers:2,leagueOutcome:'standings',matches:[],bracketRounds:[],bracketSize:0,phase:'regular',playoffView:'bracket',fixturePages:{},activeMatchId:null,reviewStage:'teams',tournamentLocked:false,tournamentCompleted:false,championId:null,championOpen:false}); }

function header(){ const label=state.music?'Desactivar ambientación':'Activar ambientación',settingsButton=state.screen==='settings'?'':`<button data-action="settings" class="header-icon-btn" aria-label="Abrir ajustes" title="Ajustes">${icons.settings}</button>`;return `<header class="topbar header-controls">${settingsButton}<button data-action="music" class="sound-btn ${state.music?'active':'muted'}" aria-label="${label}" aria-pressed="${state.music}" title="${label}"><span class="music-note">${icons.music}</span>${state.music?'':'<span class="music-off">×</span>'}</button></header>`; }
function settingsView(){ return `<section class="hero settings-view"><div class="settings-page-panel">${button('settings-back',`${icons.back} Volver`,'back gaucho-back settings-back')}<span class="settings-icon">${icons.settings}</span><p class="settings-kicker">AJUSTES DE LA MESA</p><h2>Jugamos a nuestra manera</h2><span class="settings-copy">Configurá las variantes y sonidos antes de repartir.</span><div class="settings-options"><label class="setting-row"><span><b>Puntas en 3 vs 3</b><small>Alterna Puntas y Redonda desde los 5 hasta los 24 puntos.</small></span><input data-setting="puntas" type="checkbox" ${state.puntasEnabled?'checked':''}><i></i></label><label class="setting-row"><span><b>Sonidos de interfaz</b><small>Reproduce un toque breve al presionar botones y opciones.</small></span><input data-setting="ui-sounds" type="checkbox" ${state.uiSoundsEnabled?'checked':''}><i></i></label></div><small class="settings-note">La mano termina después de 15 segundos sin modificar el marcador.</small></div></section>`; }
async function toggleAmbientMusic(){
  if(state.music){ambientAudio.pause();state.music=false;render();return;}
  try{await ambientAudio.play();state.music=true;}catch{state.music=false;}
  render();
}
function home(){ return `<section class="hero"><div class="home-menu-panel"><div class="eyebrow"><span></span> LA MESA ESTÁ SERVIDA <span></span></div><h1>Donde hay amigos,<br>hay <em>revancha.</em></h1><p>Armá el torneo, repartí las cartas y que hable la mesa.</p><div class="home-actions">${state.tournamentLocked?button('continue-tournament',`Continuar torneo ${icons.next}`,'primary huge'):button('create',`${icons.plus} Crear torneo ${icons.next}`,'primary huge')}${state.tournamentLocked?button('new-tournament',`${icons.plus} Nuevo torneo`,'secondary huge'):''}${button('scoreboard','Anotador','secondary huge')}${button('history',`${icons.history} Ver historial`,'secondary huge')}</div><div class="table-rule"><span></span><b>TRUCO</b><i></i><b>CRIOLLO</b><span></span></div></div></section>`; }
function steps(){ return `<div class="steps">${[['1','Modalidad'],['2','Jugadores'],['3','Formato'],['4','Sorteo']].map(([n,l],i)=>`<div class="step ${state.step>=+n?'on':''}"><span>${state.step>+n?icons.check:n}</span><small>${l}</small></div>${i<3?`<div class="line ${state.step>+n?'on':''}"></div>`:''}`).join('')}</div>`; }
function heading(icon, kicker, title, subtitle){ return `<div class="panel-heading"><span class="section-icon">${icons[icon]}</span><div><p>${kicker}</p><h2>${title}</h2><span>${subtitle}</span></div></div>`; }
function modePicker(){ return `<div class="panel wide-panel">${heading('users','PASO 1 DE 4','Elegí la modalidad','El formato del torneo se elige después.')}<div class="mode-grid">${modes.map(m=>`<button data-mode="${m.id}" class="mode-card ${state.mode===m.id?'selected':''}"><span class="mode-number">${m.title}</span><b>${m.name}</b><small>${m.desc}</small><span class="radio">${state.mode===m.id?'<span></span>':''}</span></button>`).join('')}</div><div class="panel-footer"><button data-action="mode-next" class="primary" ${!state.mode?'disabled':''}>Cargar jugadores ${icons.next}</button></div></div>`; }
function participants(){
  const count=players().length, size=teamSize(), min=size*2;
  const valid=isRosterValid();
  const help=count<min?`Necesitás al menos ${min} jugadores para esta modalidad.`:count%size?`La cantidad debe ser múltiplo de ${size} para formar los equipos.`:count>48?'El máximo es de 48 jugadores.':'';
  return `<div class="panel">${heading('users','PASO 2 DE 4','¿Quiénes juegan?','Sumá a todos los participantes de esta noche.')}<div class="roster-head"><b>PARTICIPANTES</b><span>${count} ${count===1?'jugador':'jugadores'}</span></div><div class="name-list">${state.names.map((n,i)=>`<div class="name-row"><span>${String(i+1).padStart(2,'0')}</span><input data-name="${i}" value="${esc(n)}" placeholder="Nombre o apodo"><button data-remove="${i}" aria-label="Eliminar">${icons.close}</button></div>`).join('')}</div>${button('add',`${icons.plus} Agregar participante`,'add-player')}${!valid?`<p class="helper">${help}</p>`:''}<div class="panel-footer"><button data-action="players-next" class="primary" ${!valid?'disabled':''}>Elegir formato ${icons.next}</button></div></div>`;
}
function groupOptions(total){ return Array.from({length:Math.max(1,Math.floor(total/2))},(_,i)=>i+1).filter(count=>Math.floor(total/count)>=2&&Math.ceil(total/count)-Math.floor(total/count)<=1); }
function recommendedGroupCount(total){ const exact=groupOptions(total).filter(count=>total%count===0&&[2,3].includes(total/count)); return exact.at(-1)||groupOptions(total).at(-1)||1; }
function qualifierOptions(total,min=2){ return [2,4,8,16,32].filter(n=>n<total&&n>=min); }
function normalizeQualifiers(total,min=2){ const options=qualifierOptions(total,min);state.qualifiers=options.includes(state.qualifiers)?state.qualifiers:(options.at(-1)||0);return options; }
function formatConfiguration(){ const total=players().length/teamSize(); if(state.format==='grupos'){const options=groupOptions(total),qualifiers=normalizeQualifiers(total,state.groupCount);return `<div class="format-config"><div><b>Cantidad de grupos</b><span>Recomendamos ${recommendedGroupCount(total)}</span></div><div class="choice-row">${options.map(n=>`<button data-group-count="${n}" class="${state.groupCount===n?'selected':''}">${n} ${n===1?'grupo':'grupos'}</button>`).join('')}</div><div><b>Clasifican a playoffs</b><span>Nunca pueden clasificar todos los equipos</span></div><div class="choice-row">${qualifiers.map(n=>`<button data-qualifiers="${n}" class="${state.qualifiers===n?'selected':''}">${n} equipos</button>`).join('')||'<span class="config-warning">No hay una llave válida para esta configuración.</span>'}</div></div>`;} if(state.format==='liga'){const qualifiers=normalizeQualifiers(total);return `<div class="format-config"><div><b>¿Cómo se define el campeón?</b><span>Podés cambiarlo antes del sorteo</span></div><div class="choice-row"><button data-league-outcome="standings" class="${state.leagueOutcome==='standings'?'selected':''}">El primero es campeón</button><button data-league-outcome="playoffs" class="${state.leagueOutcome==='playoffs'?'selected':''}">Playoffs</button></div>${state.leagueOutcome==='playoffs'?`<div><b>Clasifican</b><span>Nunca pueden clasificar todos los equipos</span></div><div class="choice-row">${qualifiers.map(n=>`<button data-qualifiers="${n}" class="${state.qualifiers===n?'selected':''}">${n} equipos</button>`).join('')||'<span class="config-warning">Se necesitan más equipos para disputar playoffs.</span>'}</div>`:''}</div>`;} return ''; }
function isFormatConfigurationValid(){ return state.format&&!(state.format==='grupos'||(state.format==='liga'&&state.leagueOutcome==='playoffs'))||state.qualifiers>0; }
function formatPicker(){ const count=players().length; return `<div class="panel wide-panel">${heading('shield',`PASO 3 DE 4 · ${count} JUGADORES`,'Elegí cómo se juega','Cada formato tiene su propia mística.')}<div class="format-grid">${formats.map(f=>`<button data-format="${f.id}" class="format-card ${state.format===f.id?'selected':''}"><span class="format-icon">${icons[f.icon]}</span><span class="format-title">${f.title}</span><span class="format-note">${f.note}</span><span class="format-desc">${f.desc}</span><span class="radio">${state.format===f.id?'<span></span>':''}</span></button>`).join('')}</div>${formatConfiguration()}<div class="panel-footer"><button data-action="confirm" class="primary" ${!isFormatConfigurationValid()?'disabled':''}>Confirmar participantes y sortear ${icons.next}</button></div></div>`; }
function createTeams(){
  const shuffled=[...players()].sort(()=>Math.random()-.5), size=teamSize();
  state.teams=[];
  for(let i=0;i<shuffled.length;i+=size){
    const members=shuffled.slice(i,i+size);
    state.teams.push({ id:`team-${i/size+1}`, name:size===1?members[0]:`Equipo ${i/size+1}`, members });
  }
}
function shuffle(list){ return [...list].sort(()=>Math.random()-.5); }
function drawGroups(){ const list=shuffle(state.teams); state.groups=Array.from({length:state.groupCount},(_,i)=>({id:`group-${i}`,name:`Grupo ${String.fromCharCode(65+i)}`,teams:[]})); list.forEach((team,i)=>state.groups[i%state.groupCount].teams.push(team)); }
function makeMatch(a,b,groupId=null,round=1,date=1){ return {id:`match-${crypto.randomUUID?.()||Math.random()}`,a:a.id,b:b.id,groupId,round,date,scoreA:null,scoreB:null,winnerId:null}; }
function roundRobin(teams,groupId=null){
  const rotation=shuffle(teams);if(rotation.length%2)rotation.push(null);
  const matches=[],rounds=rotation.length-1,half=rotation.length/2;
  for(let date=1;date<=rounds;date++){
    for(let i=0;i<half;i++){const a=rotation[i],b=rotation[rotation.length-1-i];if(a&&b)matches.push(makeMatch(a,b,groupId,1,date));}
    rotation.splice(1,0,rotation.pop());
  }
  return matches;
}
function createTournament(){
  state.matches=[];state.bracketRounds=[];state.bracketSize=0;state.phase='regular';state.playoffView='bracket';state.tournamentCompleted=false;state.championId=null;state.championOpen=false;
  if(state.format==='grupos'){drawGroups();state.groups.forEach(group=>state.matches.push(...roundRobin(group.teams,group.id)));}
  if(state.format==='liga')state.matches=roundRobin(state.teams);
  if(state.format==='eliminatoria'){
    const entrants=shuffle(state.teams), first=[];
    for(let i=0;i<entrants.length;i+=2){if(entrants[i+1]){const match=makeMatch(entrants[i],entrants[i+1],null,1);state.matches.push(match);first.push(match.id);}}
    state.bracketRounds=[first];state.bracketSize=entrants.length;state.phase='playoffs';
  }
}
function teamById(id){ return state.teams.find(team=>team.id===id); }
function standings(teams,matches){ return teams.map(team=>{const row={team,played:0,wins:0,losses:0,points:0,for:0,against:0,diff:0};matches.filter(m=>m.scoreA!==null&&(m.a===team.id||m.b===team.id)).forEach(m=>{const home=m.a===team.id,a=home?m.scoreA:m.scoreB,b=home?m.scoreB:m.scoreA;row.played++;row.for+=a;row.against+=b;if(a>b){row.wins++;row.points+=3;}else row.losses++;});row.diff=row.for-row.against;return row;}).sort((a,b)=>b.points-a.points||b.diff-a.diff); }
function tableView(teams,matches,qualified=0,highlightChampion=false){ const rows=standings(teams,matches),label=state.mode==='one'?'Participantes':'Equipos';return `<div class="standings"><div class="table-head"><span>#</span><span>${label}</span><span>PTS</span><span>J</span><span>G</span><span>P</span><span>+/-</span></div>${rows.map((row,i)=>`<div class="table-row ${i<qualified?'qualified':''} ${highlightChampion&&i===0?'champion-position':''}"><span>${i+1}</span><span class="table-team"><b>${esc(row.team.name)}</b>${state.mode==='one'?'':`<small>${row.team.members.map(esc).join(' · ')}</small>`}</span><strong>${row.points}</strong><span>${row.played}</span><span>${row.wins}</span><span>${row.losses}</span><span class="difference ${row.diff>0?'positive':row.diff<0?'negative':''}">${row.diff>0?'+':''}${row.diff}</span></div>`).join('')}${qualified?`<footer><i></i> Clasifican ${qualified} a playoffs</footer>`:highlightChampion?'<footer class="champion-legend"><i></i> El primero será campeón</footer>':''}</div>`; }
function fixturesView(matches,title='Partidos',key='main'){ const maxDate=Math.max(1,...matches.map(m=>m.date||1)),page=Math.min(state.fixturePages[key]||1,maxDate),visible=matches.filter(m=>(m.date||1)===page);state.fixturePages[key]=page;return `<aside class="fixtures"><header><button data-fixture-key="${key}" data-fixture-direction="-1" ${page===1?'disabled':''}>‹</button><span>${title}<small>Fecha ${page} de ${maxDate}</small></span><button data-fixture-key="${key}" data-fixture-direction="1" ${page===maxDate?'disabled':''}>›</button></header><div class="fixture-page">${visible.map(match=>{const a=teamById(match.a),b=teamById(match.b);return `<button ${state.tournamentLocked?`data-match="${match.id}"`:''} class="fixture ${state.tournamentLocked?'':'preview'}"><span><b>${esc(a.name)}</b><strong>${match.scoreA??'–'}</strong></span><span><b>${esc(b.name)}</b><strong>${match.scoreB??'–'}</strong></span></button>`}).join('')||'<p class="empty-fixture">Sin partidos en esta fecha</p>'}</div></aside>`; }
function groupsDashboard(){ const base=Math.floor(state.qualifiers/state.groups.length),extra=state.qualifiers%state.groups.length;return `<div class="group-dashboards">${state.groups.map((group,index)=>{const matches=state.matches.filter(m=>m.groupId===group.id),qualified=Math.min(base+(index<extra?1:0),group.teams.length);return `<section class="competition-block"><h3>${group.name}</h3><div class="competition-layout">${tableView(group.teams,matches,qualified)}${fixturesView(matches,'Partidos',group.id)}</div></section>`}).join('')}</div>`; }
function leagueDashboard(){ const standingsChampion=state.leagueOutcome==='standings';return `<div class="competition-layout">${tableView(state.teams,state.matches,standingsChampion?0:state.qualifiers,standingsChampion)}${fixturesView(state.matches,'Calendario','league')}</div>`; }
function roundName(size,index){ if(index===0&&size>8)return'Dieciseisavos';if(index===0&&size>4)return'Octavos';if(size/(2**index)>4)return'Cuartos';if(size/(2**index)>2)return'Semifinal';return'Final'; }
function bracketDashboard(){ const initial=Math.max(2,state.bracketSize||state.teams.length);const columns=[...state.bracketRounds];while(columns.length<Math.ceil(Math.log2(initial)))columns.push([]);return `<div class="bracket">${columns.map((ids,index)=>`<section><h3>${roundName(initial,index)}</h3><div class="round-matches">${ids.length?ids.map(id=>{const m=state.matches.find(x=>x.id===id),a=teamById(m.a),b=teamById(m.b);return `<button ${state.tournamentLocked&&!state.tournamentCompleted?`data-match="${m.id}"`:''} class="bracket-match ${state.tournamentLocked&&!state.tournamentCompleted?'':'preview'}"><span>${esc(a.name)} <b>${m.scoreA??'–'}</b></span><span>${esc(b.name)} <b>${m.scoreB??'–'}</b></span></button>`}).join(''):'<div class="pending-round">A definir</div>'}</div></section>`).join('')}</div>`; }
function teamsReview(){ return `<div class="tournament-dashboard team-review"><div class="dashboard-title"><p>SORTEO DE EQUIPOS</p><h2>Así quedaron los equipos</h2><span>Revisalos antes de generar el torneo.</span></div><div class="team-review-grid">${state.teams.map(team=>`<article><span>${team.name}</span>${team.members.map((member,i)=>`<div><b>${i+1}</b>${esc(member)}</div>`).join('')}</article>`).join('')}</div><div class="finish-actions">${button('reshuffle-teams','Sortear otra vez','secondary')}${button('accept-teams',`Confirmar equipos y continuar ${icons.next}`,'primary')}</div></div>`; }
function competitionReview(){ const label=formats.find(f=>f.id===state.format).title,mode=modes.find(m=>m.id===state.mode).title,canReviewGroups=state.format==='grupos'&&state.phase==='playoffs',showGroups=canReviewGroups&&state.playoffView==='groups',showBracket=state.format==='eliminatoria'||(state.phase==='playoffs'&&!showGroups),phaseNavigation=canReviewGroups?`<div class="phase-navigation">${showGroups?button('show-playoffs',`${icons.back} Volver a playoffs`,'secondary'):button('show-groups',`${icons.groups} Ver resultados de grupos`,'secondary')}</div>`:'';return `<div class="tournament-dashboard ${state.tournamentLocked?'locked':''} ${showBracket?'knockout-dashboard':''}">${state.tournamentLocked?'':`<div class="dashboard-title"><p>REVISIÓN DEL SORTEO · ${mode} · ${state.teams.length} equipos</p><h2>${label}</h2><span>Revisá el sorteo. Todavía podés cambiarlo.</span></div>`}${phaseNavigation}${showBracket?bracketDashboard():state.format==='grupos'?groupsDashboard():leagueDashboard()}${state.tournamentLocked?'':`<div class="finish-actions">${button('reshuffle-competition','Volver a sortear','secondary')}${button('lock-tournament',`Confirmar y crear torneo ${icons.check}`,'primary')}</div>`}</div>`; }
function result(){ return state.reviewStage==='teams'&&state.mode!=='one'?teamsReview():competitionReview(); }
function flow(){ if(state.tournamentLocked)return `<section class="live-tournament-wrap"><div class="live-tournament-header">${button('home',`${icons.back} Volver al inicio`,'back gaucho-back')}<span>${formats.find(f=>f.id===state.format)?.title||'Torneo'} · ${state.teams.length} equipos</span></div>${result()}</section>`;return `<section class="flow-wrap">${button('back',`${icons.back} Volver`,'back gaucho-back setup-back')}${steps()}${state.step===1?modePicker():state.step===2?participants():state.step===3?formatPicker():result()}</section>`; }

function tallyGroup(value,side){ const marks=['top','right','bottom','left','slash']; return `<span class="tally-group" data-minus="${side}" role="button" aria-label="Restar un punto">${marks.slice(0,value).map(mark=>`<i class="${mark}"></i>`).join('')}</span>`; }
function tally(score,side){ let left=score, html=''; while(left>0){const amount=Math.min(left,5);html+=tallyGroup(amount,side);left-=amount;} return html; }
function playoffEntrants(){ if(state.format==='liga')return standings(state.teams,state.matches).slice(0,state.qualifiers).map(row=>row.team);const base=Math.floor(state.qualifiers/state.groups.length),extra=state.qualifiers%state.groups.length;return state.groups.flatMap((group,index)=>standings(group.teams,state.matches.filter(match=>match.groupId===group.id)).slice(0,base+(index<extra?1:0)).map(row=>row.team)); }
function startPlayoffs(){ const entrants=shuffle(playoffEntrants()),first=[];state.phase='playoffs';state.playoffView='bracket';state.bracketSize=entrants.length;for(let i=0;i<entrants.length;i+=2){if(entrants[i+1]){const match=makeMatch(entrants[i],entrants[i+1],null,1);state.matches.push(match);first.push(match.id);}}state.bracketRounds=[first];state.fixturePages={}; }
function archiveTournament(championId){ if(state.tournamentCompleted)return;const champion=teamById(championId),entry={id:`tournament-${Date.now()}`,name:`Torneo de ${formats.find(item=>item.id===state.format).title}`,date:new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()),players:state.names.length,winner:champion.name,format:state.format,mode:state.mode,teams:structuredClone(state.teams),matches:structuredClone(state.matches),bracketRounds:structuredClone(state.bracketRounds)};history=[entry,...history.filter(item=>!item.id?.startsWith('demo-'))];localStorage.setItem(tournamentHistoryKey,JSON.stringify(history));state.tournamentCompleted=true;state.tournamentLocked=false;state.championId=championId;state.championOpen=true;state.score.winnerOpen=false;localStorage.removeItem(savedTournamentKey); }
function advanceBracket(){ const current=state.bracketRounds.at(-1)?.map(id=>state.matches.find(m=>m.id===id))||[];if(!current.length||current.some(m=>m.scoreA===null))return;if(current.length===1){archiveTournament(current[0].winnerId);return;}const winners=current.map(m=>teamById(m.winnerId)),next=[];for(let i=0;i<winners.length;i+=2)if(winners[i+1]){const match=makeMatch(winners[i],winners[i+1],null,state.bracketRounds.length+1);state.matches.push(match);next.push(match.id);}if(next.length)state.bracketRounds.push(next); }
function evaluateTournamentProgress(){ if(state.phase==='playoffs'){advanceBracket();return;}const regularMatches=state.matches.filter(match=>match.groupId||state.format==='liga');if(!regularMatches.length||regularMatches.some(match=>match.scoreA===null))return;if(state.format==='liga'&&state.leagueOutcome==='standings'){archiveTournament(standings(state.teams,state.matches)[0].team.id);return;}startPlayoffs(); }
function completeActiveMatch(side){ clearHandTimer();const match=state.matches.find(m=>m.id===state.activeMatchId);if(!match)return;match.scoreA=state.score.us;match.scoreB=state.score.them;match.winnerId=side==='us'?match.a:match.b;evaluateTournamentProgress(); }
function championModal(){ if(!state.championOpen||!state.championId)return '';const champion=teamById(state.championId);return `<div class="winner-overlay champion-overlay" role="dialog" aria-modal="true" aria-labelledby="champion-title"><div class="winner-modal champion-modal"><span class="winner-crown">${icons.trophy}</span><p>TORNEO FINALIZADO</p><h2 id="champion-title">¡${esc(champion.name)} es campeón!</h2><span>Felicitaciones por quedarse con la gloria de la mesa.</span><div class="champion-confetti"><i></i><span>GLORIA DE LA MESA</span><i></i></div>${button('view-finished-history',`${icons.history} Ver historial`,'primary winner-again')}</div></div>`; }
function winnerModal(){ if(state.championOpen)return championModal();if(!state.score.winner||!state.score.winnerOpen)return ''; const match=state.matches.find(m=>m.id===state.activeMatchId),label=match?esc(teamById(match.winnerId).name):(state.score.winner==='us'?'Nos':'Ellos'); return `<div class="winner-overlay" role="dialog" aria-modal="true" aria-labelledby="winner-title"><div class="winner-modal"><button data-action="close-winner" class="winner-close" aria-label="Cerrar">×</button><span class="winner-crown">${icons.crown}</span><p>PARTIDA TERMINADA</p><h2 id="winner-title">¡Ganó ${label}!</h2>${button(match?'return-tournament':'play-again',match?'Volver al torneo':'Volver a jugar','primary winner-again')}</div></div>`; }
function usesPuntas(){ return Boolean(state.activeMatchId&&state.mode==='three'&&state.puntasEnabled); }
function clearHandTimer(){ if(handTimer){clearTimeout(handTimer);handTimer=null;} }
function showRoundChange(){ state.score.roundNotice=true;clearTimeout(roundNoticeTimer);roundNoticeTimer=setTimeout(()=>{state.score.roundNotice=false;render();},1800); }
function finishCurrentHand(){ handTimer=null;if(!usesPuntas()||state.score.winner)return;const previous=state.score.roundType,highest=Math.max(state.score.us,state.score.them);state.score.roundType=highest>=24?'Redonda':highest>=5?(state.score.roundType==='Puntas'?'Redonda':'Puntas'):'Redonda';const match=state.matches.find(item=>item.id===state.activeMatchId);if(match)match.roundType=state.score.roundType;if(previous!==state.score.roundType)showRoundChange();saveTournament();render(); }
function scheduleHandEnd(){ clearHandTimer();if(usesPuntas()&&!state.score.winner)handTimer=setTimeout(finishCurrentHand,15000); }
function scoreboard(){ const {us,them,target}=state.score,match=state.matches.find(m=>m.id===state.activeMatchId),left=match?teamById(match.a).name:'Nos',right=match?teamById(match.b).name:'Ellos',round=usesPuntas()?`<em class="round-type ${state.score.roundType==='Puntas'?'puntas':''} ${state.score.roundNotice?'round-change':''}"><small>RONDA</small>${state.score.roundType}</em>`:''; return `<section class="scoreboard-wrap"><div class="scoreboard-top">${button(match?'match-back':'home',`${icons.back} ${match?'Volver al torneo':'Volver'}`,'back gaucho-back scoreboard-back')}<div class="target-switch"><span>PARTIDA A</span><button data-target="15" class="${target===15?'active':''}">15</button><button data-target="30" class="${target===30?'active':''}">30</button></div></div><div class="scoreboard"><header><span>${match?'PARTIDO DEL TORNEO':'ANOTADOR LIBRE'}</span>${round}<strong>Primero en llegar a ${target}</strong></header><div class="score-sides ${target===30?'target-thirty':''}"><button class="score-side us" data-score="us" aria-label="Sumar un punto a ${esc(left)}"><span class="side-label">${esc(left)}</span><strong>${us}</strong><div class="tallies">${tally(us,'us')}</div><small>TOCÁ PARA SUMAR</small></button><div class="score-divider"><span>${target}</span><i></i></div><button class="score-side them" data-score="them" aria-label="Sumar un punto a ${esc(right)}"><span class="side-label">${esc(right)}</span><strong>${them}</strong><div class="tallies">${tally(them,'them')}</div><small>TOCÁ PARA SUMAR</small></button></div><footer>${button('reset-score','Reiniciar','reset-score')}</footer></div>${winnerModal()}</section>`; }
function historyMatches(item){ if(!item.matches?.length)return '<p class="history-empty">Torneo de muestra sin resultados cargados.</p>';return `<div class="history-results">${item.matches.filter(match=>match.scoreA!==null).map(match=>{const a=item.teams.find(team=>team.id===match.a),b=item.teams.find(team=>team.id===match.b);return `<div><span>${esc(a?.name||'Participante')} <b>${match.scoreA}</b></span><i>—</i><span><b>${match.scoreB}</b> ${esc(b?.name||'Participante')}</span></div>`;}).join('')}</div>`; }
function historyDetail(item){ const mode=modes.find(value=>value.id===item.mode)?.title||'Modalidad no registrada',format=formats.find(value=>value.id===item.format)?.title||'Formato no registrado';return `<section class="flow-wrap history-wrap">${button('history-list',`${icons.back} Volver al historial`,'back gaucho-back')}<div class="panel history-detail"><header><span class="history-detail-cup">${icons.trophy}</span><p>CAMPEÓN DEL TORNEO</p><h2>${esc(item.winner)}</h2><div><span>${mode}</span><span>${format}</span><span>${item.players} jugadores</span><span>${item.date}</span></div></header>${item.teams?.length?`<section class="history-section"><h3>${item.mode==='one'?'Participantes':'Equipos'}</h3><div class="history-roster">${item.teams.map(team=>`<div><b>${esc(team.name)}</b>${item.mode==='one'?'':`<small>${team.members.map(esc).join(' · ')}</small>`}</div>`).join('')}</div></section>`:''}<section class="history-section"><h3>Todos los resultados</h3>${historyMatches(item)}</section><footer>Este torneo está finalizado y es de solo lectura.</footer></div></section>`; }
function historyView(){ const selected=history.find(item=>item.id===state.selectedHistoryId);if(selected)return historyDetail(selected);return `<section class="flow-wrap history-wrap">${button('home',`${icons.back} Volver al inicio`,'back gaucho-back')}<div class="panel history-panel">${heading('history','MEMORIAS DE LA MESA','Historial','Elegí un torneo para consultar todos sus detalles.')}<div class="history-list">${history.map(h=>{const mode=modes.find(value=>value.id===h.mode)?.title||'Modalidad sin registrar',format=formats.find(value=>value.id===h.format)?.title||'Torneo';return `<button class="history-card" data-history-id="${h.id}"><span class="history-cup">${icons.trophy}</span><span class="history-card-copy"><small>${format} · ${mode}</small><b>${esc(h.name)}</b><em>${h.date} · ${h.players} jugadores</em></span><span class="winner"><small>CAMPEÓN</small><b>${esc(h.winner)}</b></span><span class="history-arrow">${icons.next}</span></button>`;}).join('')||'<p class="history-empty">Todavía no terminó ningún torneo.</p>'}</div></div></section>`; }
function playClickSound(){ if(!state.uiSoundsEnabled)return;try{uiAudioContext=uiAudioContext||new (window.AudioContext||window.webkitAudioContext)();const now=uiAudioContext.currentTime,oscillator=uiAudioContext.createOscillator(),gain=uiAudioContext.createGain();oscillator.type='triangle';oscillator.frequency.setValueAtTime(240,now);oscillator.frequency.exponentialRampToValueAtTime(105,now+.055);gain.gain.setValueAtTime(.055,now);gain.gain.exponentialRampToValueAtTime(.001,now+.065);oscillator.connect(gain).connect(uiAudioContext.destination);oscillator.start(now);oscillator.stop(now+.07);}catch{} }
function render(){ const signature=[state.screen,state.step,state.reviewStage,state.playoffView,state.selectedHistoryId||''].join('-'),transitioning=signature!==lastViewSignature;lastViewSignature=signature;const content=state.screen==='home'?home():state.screen==='settings'?settingsView():state.screen==='create'?flow():state.screen==='scoreboard'?scoreboard():historyView();root.innerHTML=`<main class="app-shell"><div class="backdrop"></div>${header()}<div class="view-stage ${transitioning?'view-enter':''}">${content}</div></main>`; }
function goHome(){ clearHandTimer();if(state.tournamentLocked){saveTournament();state.screen='home';state.activeMatchId=null;}else Object.assign(state,{screen:'home',step:1,mode:'',format:'',teams:[],groups:[],matches:[],bracketRounds:[],fixturePages:{},activeMatchId:null,reviewStage:'teams',tournamentLocked:false});render(); }

root.addEventListener('input',e=>{ if(e.target.dataset.name!==undefined) state.names[+e.target.dataset.name]=e.target.value; });
root.addEventListener('change',e=>{ if(e.target.dataset.setting==='puntas'){playClickSound();state.puntasEnabled=e.target.checked;localStorage.setItem('truco-criollo-puntas',String(state.puntasEnabled));if(!state.puntasEnabled){clearHandTimer();state.score.roundType='Redonda';const match=state.matches.find(item=>item.id===state.activeMatchId);if(match)match.roundType='Redonda';}render();}if(e.target.dataset.setting==='ui-sounds'){state.uiSoundsEnabled=e.target.checked;localStorage.setItem('truco-criollo-ui-sounds',String(state.uiSoundsEnabled));if(state.uiSoundsEnabled)playClickSound();render();} });
root.addEventListener('keydown',e=>{ if(e.target.dataset.name!==undefined&&e.key==='Enter'){state.names.push('');render();setTimeout(()=>document.querySelector('.name-row:last-child input')?.focus());} });
root.addEventListener('click',e=>{
  if(e.target.closest('button'))playClickSound();
  const remove=e.target.closest('[data-remove]'), format=e.target.closest('[data-format]'), mode=e.target.closest('[data-mode]'), match=e.target.closest('[data-match]'), historyCard=e.target.closest('[data-history-id]'), fixtureNav=e.target.closest('[data-fixture-key]'), groupCount=e.target.closest('[data-group-count]'), qualifiers=e.target.closest('[data-qualifiers]'), leagueOutcome=e.target.closest('[data-league-outcome]'), score=e.target.closest('[data-score]'), minus=e.target.closest('[data-minus]'), target=e.target.closest('[data-target]'), action=e.target.closest('[data-action]')?.dataset.action;
  if(remove){state.names.splice(+remove.dataset.remove,1);if(!state.names.length)state.names=[''];render();return;}
  if(format){state.format=format.dataset.format;const total=players().length/teamSize();state.groupCount=recommendedGroupCount(total);state.qualifiers=qualifierOptions(total,state.format==='grupos'?state.groupCount:2).at(-1)||0;render();return;}
  if(mode){state.mode=mode.dataset.mode;render();return;}
  if(groupCount){state.groupCount=+groupCount.dataset.groupCount;normalizeQualifiers(players().length/teamSize(),state.groupCount);render();return;}
  if(qualifiers){state.qualifiers=+qualifiers.dataset.qualifiers;render();return;}
  if(leagueOutcome){state.leagueOutcome=leagueOutcome.dataset.leagueOutcome;render();return;}
  if(match){clearHandTimer();const selected=state.matches.find(m=>m.id===match.dataset.match);state.activeMatchId=selected.id;state.score.us=selected.scoreA??0;state.score.them=selected.scoreB??0;state.score.roundType=selected.roundType||'Redonda';state.score.roundNotice=false;state.score.winner=selected.winnerId?(selected.winnerId===selected.a?'us':'them'):null;state.score.winnerOpen=false;state.screen='scoreboard';render();return;}
  if(historyCard){state.selectedHistoryId=historyCard.dataset.historyId;render();return;}
  if(fixtureNav){const key=fixtureNav.dataset.fixtureKey;state.fixturePages[key]=Math.max(1,(state.fixturePages[key]||1)+Number(fixtureNav.dataset.fixtureDirection));saveTournament();render();return;}
  if(minus){const side=minus.dataset.minus;if(!state.score.winner){state.score[side]=Math.max(0,state.score[side]-1);scheduleHandEnd();}render();return;}
  if(score){const side=score.dataset.score;if(!state.score.winner&&state.score[side]<state.score.target){state.score[side]++;if(state.score[side]===state.score.target){state.score.winner=side;state.score.winnerOpen=true;completeActiveMatch(side);saveTournament();}else scheduleHandEnd();}render();return;}
  if(target){state.score.target=+target.dataset.target;state.score.us=Math.min(state.score.us,state.score.target);state.score.them=Math.min(state.score.them,state.score.target);state.score.winner=null;state.score.winnerOpen=false;render();return;}
  if(action==='home')goHome();
  if(action==='music')toggleAmbientMusic();
  if(action==='settings'){clearHandTimer();state.settingsReturnScreen=state.screen;state.screen='settings';render();}
  if(action==='settings-back'){state.screen=state.settingsReturnScreen||'home';render();}
  if(action==='create'){state.screen='create';render();}
  if(action==='continue-tournament'){state.screen='create';state.step=4;render();}
  if(action==='new-tournament'){resetTournament();render();}
  if(action==='scoreboard'){state.screen='scoreboard';render();}
  if(action==='history'){state.selectedHistoryId=null;state.screen='history';render();}
  if(action==='history-list'){state.selectedHistoryId=null;render();}
  if(action==='show-groups'){state.playoffView='groups';saveTournament();render();}
  if(action==='show-playoffs'){state.playoffView='bracket';saveTournament();render();}
  if(action==='view-finished-history'){state.championOpen=false;state.activeMatchId=null;state.selectedHistoryId=null;state.screen='history';render();}
  if(action==='match-back'||action==='return-tournament'){clearHandTimer();state.screen='create';state.activeMatchId=null;state.score.winnerOpen=false;render();}
  if(action==='add'&&state.names.length<48){state.names.push('');render();setTimeout(()=>document.querySelector('.name-row:last-child input')?.focus());}
  if(action==='back'){if(state.step===1)goHome();else{state.step--;render();}}
  if(action==='mode-next'&&state.mode){state.step=2;render();}
  if(action==='players-next'&&isRosterValid()){state.step=3;render();}
  if(action==='confirm'&&state.format&&isRosterValid()&&isFormatConfigurationValid()){createTeams();state.tournamentLocked=false;if(state.mode==='one'){createTournament();state.reviewStage='competition';}else state.reviewStage='teams';state.step=4;render();}
  if(action==='reshuffle-teams'){createTeams();render();}
  if(action==='accept-teams'){createTournament();state.reviewStage='competition';render();}
  if(action==='reshuffle-competition'){createTournament();render();}
  if(action==='lock-tournament'){state.tournamentLocked=true;saveTournament();render();}
  if(action==='reset-score'||action==='play-again'){clearHandTimer();state.score.us=0;state.score.them=0;state.score.roundType='Redonda';state.score.roundNotice=false;state.score.winner=null;state.score.winnerOpen=false;render();}
  if(action==='close-winner'){state.score.winnerOpen=false;render();}
});
restoreTournament();
render();
